version: '3.5'
services:
  pz-server:
     build: .
     restart: "on-failure:5"
     network_mode: "host"
     volumes:
        - ./Server:/root/Zomboid/Server
     stdin_open: true 
     tty: true
     stop_grace_period: 6m

