version: '3.5'
services:
  dst-server:
     build: .
     restart: "on-failure:5"
   #   netstat -tulpn
     ports:
        - "27015-27030:27015-27030/tcp"
        - "27036-27037:27036-27037/tcp"
        - "6587:6587"
        - "4380:4380"
        - "27000-27036:27000-27036/udp"
     network_mode: "host"
     volumes:
        - ./ServerSetting.ini:/root/craftopia_server/ServerSetting.ini
        - ./DedicatedServerSave:/root/craftopia_server/DedicatedServerSave
     stdin_open: true 
     tty: true
     stop_grace_period: 6m

