version: '3.5'
services:
  dst-server:
     build: .
     restart: "on-failure:5"
   #   netstat -tulpn
     ports:
        - "42715-42730:42715-42730/tcp"
        - "6587:6587/tcp"
        - "4380:4380/udp"
        - "59500-59536:59500-59536/udp"
     volumes:
        - ./ServerSetting.ini:/root/craftopia_server/ServerSetting.ini
        - ./DedicatedServerSave:/root/craftopia_server/DedicatedServerSave
     stop_grace_period: 6m

