version: '3.5'
services:
  dst-server:
     build: .
     restart: "on-failure:5"
     ports:
        - "27015-27030:27015-27030/tcp"
        - "6587:6587/tcp"
        - "4380:4380/udp"
        - "27000-27031:27000-27031/udp"
        - "27036:27036/udp"
     volumes:
        - ./ServerSetting.ini:/root/craftopia_server/ServerSetting.ini
        - ./DedicatedServerSave:/root/craftopia_server/DedicatedServerSave
     stop_grace_period: 6m

