version: '3.5'
services:
  dst-server:
     build: .
     restart: "on-failure:5"
     network_mode: "host"
     volumes:
        - ./Saved:/root/ark_server/ShooterGame/Saved/
        - ./GameUserSettings.ini:/root/ark_server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
     stdin_open: true 
     tty: true
     stop_grace_period: 6m

